apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: master
  template:
    metadata:
      labels:
        app: postgres
        role: master
    spec:
      initContainers:
        - name: volume-permissions
          image: bitnami/postgresql:15
          command:
            - /bin/bash
            - -ec
            - |
              chown -R 1001:1001 /bitnami/postgresql
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data-pvc
              mountPath: /bitnami/postgresql
#      securityContext:
#        fsGroup: 1001
      containers:
        - name: postgres
          image: bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:

            - name: POSTGRESQL_REPLICATION_MODE
              value: "master"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_pass"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              value: "postgres"
            - name: POSTGRESQL_DATABASE
              value: "mydb"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"

          volumeMounts:
            - name: data-pvc
              mountPath: /bitnami/postgresql

  volumeClaimTemplates:
    - metadata:
        name: data-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
    role: replica
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
spec:
  serviceName: "postgres-replica"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      role: replica
  template:
    metadata:
      labels:
        app: postgres
        role: replica
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: "slave"
            - name: POSTGRESQL_MASTER_HOST
              value: "postgres-replica-0.postgres-replica"
            - name: POSTGRESQL_MASTER_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_pass"
          volumeMounts:
            - name: data-pvc-replica
              mountPath: /bitnami/postgresql

  volumeClaimTemplates:
    - metadata:
        name: data-pvc-replica
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  name: postgres-master
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
    role: master


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
spec:
  serviceName: "postgres-slave"
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      role: new-slave
  template:
    metadata:
      labels:
        app: postgres
        role: new-slave
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: "slave"
            - name: POSTGRESQL_MASTER_HOST
              value: "postgres-0.postgres-master"

            - name: POSTGRESQL_MASTER_PORT_NUMBER
              value: "5432"
            - name: POSTGRESQL_REPLICATION_USER
              value: "repl_user"
            - name: POSTGRESQL_REPLICATION_PASSWORD
              value: "repl_pass"
            - name: POSTGRESQL_USERNAME
              value: "postgres"
            - name: POSTGRESQL_PASSWORD
              value: "postgres"
            - name: POSTGRESQL_DATABASE
              value: "mydb"
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
          volumeMounts:
            - name: data-pvc-slave
              mountPath: /bitnami/postgresql
  volumeClaimTemplates:
    - metadata:
        name: data-pvc-slave
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
spec:
  ports:
    - port: 5432
      name: postgres
  clusterIP: None
  selector:
    app: postgres
    role: new-slave
